### ISSUE TITLE
I downloaded install everything but commands doesn't work

### ISSUE THREAD

**Issue by NevilYT** [Rudokhvist/SelectiveLootAndTransferPlugin#7]
I downloaded the pluging install it, it is in plugin section.
![image](https://github.com/user-attachments/assets/bd71c722-ba06-4457-8060-b6a2564f310b)
![image](https://github.com/user-attachments/assets/444e4a86-bca0-48e7-9285-7b5dbfb2e7dd)

**Comment by Rudokhvist** [comment]
ASF-ui's help command only shows help for ASF commands, not for plugin commands.
And there is no transfer# command without parameters, so you are getting "Unknown command" response. 
So far from what I see - everything works exactly as it should.

**Comment by NevilYT** [comment]
![image](https://github.com/user-attachments/assets/a5df65af-36ba-4fe9-8511-574dd09813bf)

**Comment by Rudokhvist** [comment]
Ok, can confirm, seams to be incompatible with latest version. Will work on it, thank you for report!

**Comment by Rudokhvist** [comment]
Please check if release 1.0.0.1 fixes your issue.

**Comment by NevilYT** [comment]
So when I try to loot# account A it says my inventory is empty but there are RUST items that I try to loot to master account and mode is A which is all items
![image](https://github.com/user-attachments/assets/d0a971be-3048-4a5f-a8ec-f06d20d8aebe)
![image](https://github.com/user-attachments/assets/706815e0-947d-4b8a-adb9-c1b0b76fc703)

**Comment by NevilYT** [comment]
And if it possible can you make like loot# All A so all items from all turned on accounts would go to master account, I would really appreciate it)

**Comment by Rudokhvist** [comment]
This plugin is only for community items, it won't help you with items from RUST or other games. But good news is that regular ASF loot^ and transfer^ commands will do what you want - transfer items from other games (one inventory tab at a time though).
